version: "3.9"
services:
  database:
    image: "postgres:14.0-alpine"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - ./local-db-setup/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

